# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scanner.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1217, 716)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 1021, 631))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(20, 0, 20, 0)
        self.gridLayout.setSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.outPic = QtWidgets.QLabel(self.gridLayoutWidget)
        self.outPic.setAlignment(QtCore.Qt.AlignCenter)
        self.outPic.setObjectName("outPic")
        self.gridLayout.addWidget(self.outPic, 0, 2, 1, 1)
        self.BTNpickPic = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.BTNpickPic.setObjectName("BTNpickPic")
        self.gridLayout.addWidget(self.BTNpickPic, 1, 0, 1, 1)
        self.rawPic = QtWidgets.QLabel(self.gridLayoutWidget)
        self.rawPic.setTextFormat(QtCore.Qt.AutoText)
        self.rawPic.setAlignment(QtCore.Qt.AlignCenter)
        self.rawPic.setObjectName("rawPic")
        self.gridLayout.addWidget(self.rawPic, 0, 0, 1, 1)
        self.BTNgetPic = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.BTNgetPic.setObjectName("BTNgetPic")
        self.gridLayout.addWidget(self.BTNgetPic, 1, 2, 1, 1)
        self.BTNpicBox = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.BTNpicBox.setObjectName("BTNpicBox")
        self.gridLayout.addWidget(self.BTNpicBox, 1, 1, 1, 1)
        self.boxedPic = QtWidgets.QLabel(self.gridLayoutWidget)
        self.boxedPic.setAlignment(QtCore.Qt.AlignCenter)
        self.boxedPic.setObjectName("boxedPic")
        self.gridLayout.addWidget(self.boxedPic, 0, 1, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1060, 610, 131, 31))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.BTNsavePic = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.BTNsavePic.setObjectName("BTNsavePic")
        self.verticalLayout.addWidget(self.BTNsavePic)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1217, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.BTNpickPic.clicked.connect(MainWindow.pickPic_clicked)
        self.BTNpicBox.clicked.connect(MainWindow.pickBox_clicked)
        self.BTNgetPic.clicked.connect(MainWindow.resultPic_clicked)
        self.BTNsavePic.clicked.connect(MainWindow.savePic_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "弟中之弟扫描器"))
        self.outPic.setText(_translate("MainWindow", "输出图片"))
        self.BTNpickPic.setText(_translate("MainWindow", "选择图片"))
        self.rawPic.setText(_translate("MainWindow", "初始图片"))
        self.BTNgetPic.setText(_translate("MainWindow", "处理图片"))
        self.BTNpicBox.setText(_translate("MainWindow", "选择边框"))
        self.boxedPic.setText(_translate("MainWindow", "边框图片"))
        self.BTNsavePic.setText(_translate("MainWindow", "保存生成结果"))
